### ISSUE TITLE
what is resource group?

### ISSUE THREAD

**Issue by JQuarticx** [FourTimes/azure-practice#13]

**Comment by Joe-Joy** [comment]
@Joe-Joy
### Resource Group:- 
- A container that holds related resources for an Azure solution. The resource group includes those resources that you want to manage as a group. You decide which resources belong in a resource group based on what makes the most sense for your organization.
### Some Important Factors:-

1. All the resources in your resource group should share the same lifecycle. You deploy, update, and delete them together. If one resource, such as a server, needs to exist on a different deployment cycle it should be in another resource group.

2. Each resource can exist in only one resource group.
3. You can add or remove a resource to a resource group at any time.
4. You can move a resource from one resource group to another group.
5. The resources in a resource group can be located in different regions than the resource group.
6. When you create a resource group, you need to provide a location for that resource group.
7. A resource can connect to resources in other resource groups.
8. When you delete a resource group, all resources in the resource group are also deleted.
9. You can deploy up to 800 instances of a resource type in each resource group. 
10. Some resources can exist outside of a resource group. These resources are deployed to the subscription, management group, or tenant. Only specific resource types are supported at these scopes.
11. To create a resource group, you can use the portal, PowerShell, Azure CLI, or an ARM template.

**Comment by vijaybaskarnov1995** [comment]
resource group is a container that holds related resources in Azure

When a user sends a request from any of the Azure tools, APIs, or SDKs, Resource Manager receives the request. It authenticates and authorizes the request. Resource Manager sends the request to the Azure service, which takes the requested action. Because all requests are handled through the same API, you see consistent results and capabilities in all the different tools.
